wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1650556861
    t:
      1:
      - 55
      2:
      - 55
      4: 3.8.13
      5: 0.12.14
      8:
      - 5
